### ISSUE TITLE
Updating example code on Access Control

### ISSUE THREAD

**Issue by svskaushik** [OpenZeppelin/openzeppelin-docs#309]
The code example at [https://docs.openzeppelin.com/contracts/2.x/access-control](url) imports Ownable.sol in the following fashion:

`import "@openzeppelin/contracts/ownership/Ownable.sol";`

I believe to be in line with the current structure of OpenZeppelin contracts the import should be done as below:

`import "@openzeppelin/contracts/access/Ownable.sol";`

**Comment by frangio** [comment]
The page you link is for versions 2.x of OpenZeppelin Contracts. The latest can be found at https://docs.openzeppelin.com/contracts/4.x/access-control.
