### ISSUE TITLE
Indexed modiffier missing on events

### ISSUE THREAD

**Issue by cytadela8** [OpenZeppelin/openzeppelin-docs#311]
docs.openzeppelin.com doesn't show indexed modifier of events. Example: ERC20 Transfer event [on docs site](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#IERC20-Transfer-address-address-uint256-) vs [in sources](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol#L75). I believe this issue applies to all contracts with indexed events. Indexed modifier is simply omitted in generated docs.

**Comment by frangio** [comment]
Thank you @cytadela8. This is something we have to add in the template for docgen:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/docs/contract.hbs#L87

**Comment by JulissaDantes** [comment]
This is being worked on [#3958](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3958)

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3958.
