### ISSUE TITLE
Missing nile docs page

### ISSUE THREAD

**Issue by microbecode** [OpenZeppelin/openzeppelin-docs#340]
The documentation site used to have a page https://docs.openzeppelin.com/nile but it doesn't exist anymore. This is linked to for example at https://github.com/OpenZeppelin/nile . Couldn't find the right place it should link to currently.

**Comment by frangio** [comment]
It wasn't ready yet. :slightly_smiling_face:

It was just merged in #339! Should be up in a couple of minutes.
