### ISSUE TITLE
ERC-165 docs are outdated

### ISSUE THREAD

**Issue by PaulRBerg** [OpenZeppelin/openzeppelin-docs#409]
The docs on ERC-165 reference a function called `_regiterInterface` that no longer exists in the latest version of OpenZeppelin (v5.0.2 at the time of opening this issue):

https://docs.openzeppelin.com/contracts/2.x/api/introspection#ERC165-_registerInterface-bytes4-

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.2/contracts/utils/introspection/ERC165.sol

**Comment by frangio** [comment]
> https://docs.openzeppelin.com/contracts/2.x/api/introspection#ERC165-_registerInterface-bytes4-

These are the docs for v2 (see the URL and at the top left in the site).

**Comment by PaulRBerg** [comment]
sorry, missed that. I arrived there via Google
